# Generated by Django 5.2.11 on 2026-07-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE SEQUENCE employee_number_seq
                START WITH 1
                INCREMENT BY 1;
            """,
            reverse_sql="""
                DROP SEQUENCE employee_number_seq;
            """,
        ),
    ]