# Generated by Django 5.2.11 on 2026-08-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0003_add_status_field_and_update_role_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.CharField(choices=[('EXEMPT', 'Exempt'), ('ENGINEERING', 'Engineering'), ('FINANCE', 'Finance'), ('ACCOUNTING', 'Accounting'), ('LEGAL', 'Legal')], default='Department.ENGINEERING', max_length=25),
        ),
    ]
