[pytest]
DJANGO_SETTINGS_MODULE = config.settings

python_files =
    tests.py
    test_*.py
    *_test.py*
    *_tests.py

python_classes = Test*
python_functions = test_*

testpaths =
    authcore
    common

django_find_project = true

# Coverage
addopts =
    --ds=config.settings
    --cov=.
    --cov-report=term-missing
    --cov-fail-under=50
    --verbose
    --tb=short
    --strict-markers
    -p no:warnings


markers =
    unit: unit tests
    integration: integration tests
    
    
# Celery test configuration
celery_task_always_eager = true
celery_task_eager_propagates = true